### PR TITLE
New plugin registration mechanism

### PR DESCRIPTION
**Pull request by stv0g**

### CODE REVIEW

**Comment by stv0g** [comment]
@n-eiling did you had a chance to review the PR? Or should we skip reviews?

**Comment by n-eiling** [comment]
I think most of this is already on master because you  pushed it there. Please check / rebase.

**Comment by stv0g** [comment]
Hi @n-eiling,

I rebased this PR on master and gave it a thorough review myself. Can you also have a look and merge it?

**Comment by n-eiling** [comment]
I tested your changes. I would like to merge #75 first to be make the master be error-free as early as possible. Your branch (this PR) rebases cleanly to fix/vfio-crashes so let's merge #75 and then this.

**Review by n-eiling — APPROVED** [review]

**Pull request merged**
